### ISSUE TITLE
Annual Budget - prep, variance, and new version. 

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Finance-project-issues#7]
From the report: "An   annual organisational budget is not prepared or approved by the trustees." 

Recommendation: "An annual budget should be prepared and approved by the trustees before the start of the financial year. This ensures the trustees have oversight of the organisation’s annual finances, can assess whether all planned costs are adequately funded and are then able to monitor the financial performance of eQuality Time against the approved annual budget." 

Action: This budget was prepared earlier in the year: 
[Organisational Budget.pdf](https://github.com/eQualityTime/Finance-project-issues/files/3515277/Organisational.Budget.pdf)

# Todo
- [x] Review the annual budget and check for ways in which it was different (varience analysis) 
- [ ] Have a folder for anual budgets in Dropbox or on Website with notes 
- [x]  Prepare new budget for the following year and email to trustees 
- [x] get approved 
- [x] Calendar event to check this in future.

**Comment by joereddington-public** [comment]
Last organisational budget is here: http://equalitytime.co.uk/6383/2019/10/07/organisational-budget-for-2019-2020/
